trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  displayName: 'Flutter Install'

- task: FlutterTest@0
  inputs:
    projectDirectory: '.'
  displayName: 'Flutter Test'

- task: FlutterBuild@0
  inputs:
    target: 'all'
    projectDirectory: '.'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing the Artifact: drop'
